# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insertarCaso.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VentanaCaso(object):
    def setupUi(self, VentanaCaso):
        VentanaCaso.setObjectName("VentanaCaso")
        VentanaCaso.resize(500, 240)
        VentanaCaso.setMinimumSize(QtCore.QSize(500, 240))
        VentanaCaso.setMaximumSize(QtCore.QSize(500, 240))
        font = QtGui.QFont()
        font.setPointSize(14)
        VentanaCaso.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(VentanaCaso)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(VentanaCaso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.inputCredencial = QtWidgets.QLineEdit(VentanaCaso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputCredencial.sizePolicy().hasHeightForWidth())
        self.inputCredencial.setSizePolicy(sizePolicy)
        self.inputCredencial.setObjectName("inputCredencial")
        self.horizontalLayout_2.addWidget(self.inputCredencial)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(5, 5, 10, 5)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(VentanaCaso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.inputMontante = QtWidgets.QLineEdit(VentanaCaso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputMontante.sizePolicy().hasHeightForWidth())
        self.inputMontante.setSizePolicy(sizePolicy)
        self.inputMontante.setObjectName("inputMontante")
        self.horizontalLayout_3.addWidget(self.inputMontante)
        self.label_3 = QtWidgets.QLabel(VentanaCaso)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.botonAceptar = QtWidgets.QPushButton(VentanaCaso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonAceptar.sizePolicy().hasHeightForWidth())
        self.botonAceptar.setSizePolicy(sizePolicy)
        self.botonAceptar.setMinimumSize(QtCore.QSize(200, 40))
        self.botonAceptar.setMaximumSize(QtCore.QSize(200, 40))
        self.botonAceptar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonAceptar.setObjectName("botonAceptar")
        self.horizontalLayout_4.addWidget(self.botonAceptar)
        self.botonCancelar = QtWidgets.QPushButton(VentanaCaso)
        self.botonCancelar.setMinimumSize(QtCore.QSize(100, 40))
        self.botonCancelar.setMaximumSize(QtCore.QSize(100, 40))
        self.botonCancelar.setObjectName("botonCancelar")
        self.horizontalLayout_4.addWidget(self.botonCancelar)
        self.botonResetear = QtWidgets.QPushButton(VentanaCaso)
        self.botonResetear.setMinimumSize(QtCore.QSize(150, 40))
        self.botonResetear.setMaximumSize(QtCore.QSize(150, 40))
        self.botonResetear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonResetear.setObjectName("botonResetear")
        self.horizontalLayout_4.addWidget(self.botonResetear)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)

        self.retranslateUi(VentanaCaso)
        QtCore.QMetaObject.connectSlotsByName(VentanaCaso)

    def retranslateUi(self, VentanaCaso):
        _translate = QtCore.QCoreApplication.translate
        VentanaCaso.setWindowTitle(_translate("VentanaCaso", "Insertar un Caso Judicial"))
        self.label.setText(_translate("VentanaCaso", "Número de Credencial"))
        self.label_2.setText(_translate("VentanaCaso", "Montante del Caso"))
        self.label_3.setText(_translate("VentanaCaso", "€"))
        self.botonAceptar.setText(_translate("VentanaCaso", "Insertar Caso Judicial"))
        self.botonCancelar.setText(_translate("VentanaCaso", "Cancelar"))
        self.botonResetear.setText(_translate("VentanaCaso", "Resetear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaCaso = QtWidgets.QDialog()
    ui = Ui_VentanaCaso()
    ui.setupUi(VentanaCaso)
    VentanaCaso.show()
    sys.exit(app.exec_())

