# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insertarRelacion.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_insertarRelacion(object):
    def setupUi(self, insertarRelacion):
        insertarRelacion.setObjectName("insertarRelacion")
        insertarRelacion.resize(580, 400)
        insertarRelacion.setMinimumSize(QtCore.QSize(580, 400))
        insertarRelacion.setMaximumSize(QtCore.QSize(580, 400))
        self.gridLayout = QtWidgets.QGridLayout(insertarRelacion)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.botonAceptar = QtWidgets.QPushButton(insertarRelacion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonAceptar.sizePolicy().hasHeightForWidth())
        self.botonAceptar.setSizePolicy(sizePolicy)
        self.botonAceptar.setMinimumSize(QtCore.QSize(200, 40))
        self.botonAceptar.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.botonAceptar.setFont(font)
        self.botonAceptar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonAceptar.setObjectName("botonAceptar")
        self.horizontalLayout_2.addWidget(self.botonAceptar)
        self.botonCancelar = QtWidgets.QPushButton(insertarRelacion)
        self.botonCancelar.setMinimumSize(QtCore.QSize(100, 40))
        self.botonCancelar.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.botonCancelar.setFont(font)
        self.botonCancelar.setObjectName("botonCancelar")
        self.horizontalLayout_2.addWidget(self.botonCancelar)
        self.botonResetear = QtWidgets.QPushButton(insertarRelacion)
        self.botonResetear.setMinimumSize(QtCore.QSize(150, 40))
        self.botonResetear.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.botonResetear.setFont(font)
        self.botonResetear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonResetear.setObjectName("botonResetear")
        self.horizontalLayout_2.addWidget(self.botonResetear)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelSeleciona = QtWidgets.QLabel(insertarRelacion)
        self.labelSeleciona.setMinimumSize(QtCore.QSize(500, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelSeleciona.setFont(font)
        self.labelSeleciona.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSeleciona.setWordWrap(True)
        self.labelSeleciona.setObjectName("labelSeleciona")
        self.verticalLayout.addWidget(self.labelSeleciona)
        self.labelCampo = QtWidgets.QLabel(insertarRelacion)
        self.labelCampo.setMinimumSize(QtCore.QSize(500, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelCampo.setFont(font)
        self.labelCampo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCampo.setObjectName("labelCampo")
        self.verticalLayout.addWidget(self.labelCampo)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tablaRegistros = QtWidgets.QTableWidget(insertarRelacion)
        self.tablaRegistros.setMinimumSize(QtCore.QSize(500, 205))
        self.tablaRegistros.setMaximumSize(QtCore.QSize(16777215, 205))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tablaRegistros.setFont(font)
        self.tablaRegistros.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.tablaRegistros.setLineWidth(5)
        self.tablaRegistros.setMidLineWidth(5)
        self.tablaRegistros.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tablaRegistros.setAlternatingRowColors(True)
        self.tablaRegistros.setGridStyle(QtCore.Qt.SolidLine)
        self.tablaRegistros.setRowCount(5)
        self.tablaRegistros.setColumnCount(2)
        self.tablaRegistros.setObjectName("tablaRegistros")
        self.tablaRegistros.horizontalHeader().setVisible(False)
        self.tablaRegistros.horizontalHeader().setDefaultSectionSize(200)
        self.tablaRegistros.horizontalHeader().setStretchLastSection(True)
        self.tablaRegistros.verticalHeader().setVisible(False)
        self.tablaRegistros.verticalHeader().setDefaultSectionSize(40)
        self.tablaRegistros.verticalHeader().setMinimumSectionSize(40)
        self.tablaRegistros.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tablaRegistros, 1, 0, 1, 1)

        self.retranslateUi(insertarRelacion)
        QtCore.QMetaObject.connectSlotsByName(insertarRelacion)

    def retranslateUi(self, insertarRelacion):
        _translate = QtCore.QCoreApplication.translate
        insertarRelacion.setWindowTitle(_translate("insertarRelacion", "Dialog"))
        self.botonAceptar.setText(_translate("insertarRelacion", "Insertar Relación"))
        self.botonCancelar.setText(_translate("insertarRelacion", "Cancelar"))
        self.botonResetear.setText(_translate("insertarRelacion", "Resetear"))
        self.labelSeleciona.setText(_translate("insertarRelacion", "Selecciona los Registros relacionados con:"))
        self.labelCampo.setText(_translate("insertarRelacion", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    insertarRelacion = QtWidgets.QDialog()
    ui = Ui_insertarRelacion()
    ui.setupUi(insertarRelacion)
    insertarRelacion.show()
    sys.exit(app.exec_())

