# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insertarImputado.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_insertarImputado(object):
    def setupUi(self, insertarImputado):
        insertarImputado.setObjectName("insertarImputado")
        insertarImputado.resize(600, 380)
        insertarImputado.setMinimumSize(QtCore.QSize(600, 380))
        insertarImputado.setMaximumSize(QtCore.QSize(600, 380))
        font = QtGui.QFont()
        font.setPointSize(14)
        insertarImputado.setFont(font)
        insertarImputado.setSizeGripEnabled(False)
        self.gridLayout_4 = QtWidgets.QGridLayout(insertarImputado)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.labelNombre = QtWidgets.QLabel(insertarImputado)
        self.labelNombre.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNombre.setObjectName("labelNombre")
        self.gridLayout.addWidget(self.labelNombre, 0, 0, 1, 1)
        self.inputNombre = QtWidgets.QLineEdit(insertarImputado)
        self.inputNombre.setObjectName("inputNombre")
        self.gridLayout.addWidget(self.inputNombre, 0, 1, 1, 1)
        self.labelApellidos = QtWidgets.QLabel(insertarImputado)
        self.labelApellidos.setAlignment(QtCore.Qt.AlignCenter)
        self.labelApellidos.setObjectName("labelApellidos")
        self.gridLayout.addWidget(self.labelApellidos, 1, 0, 1, 1)
        self.inputApellidos = QtWidgets.QLineEdit(insertarImputado)
        self.inputApellidos.setObjectName("inputApellidos")
        self.gridLayout.addWidget(self.inputApellidos, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelPartido = QtWidgets.QLabel(insertarImputado)
        self.labelPartido.setMinimumSize(QtCore.QSize(0, 35))
        self.labelPartido.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPartido.setObjectName("labelPartido")
        self.gridLayout_2.addWidget(self.labelPartido, 0, 0, 1, 1)
        self.inputPartido = QtWidgets.QComboBox(insertarImputado)
        self.inputPartido.setMinimumSize(QtCore.QSize(400, 35))
        self.inputPartido.setObjectName("inputPartido")
        self.gridLayout_2.addWidget(self.inputPartido, 0, 1, 1, 1)
        self.labelCargo = QtWidgets.QLabel(insertarImputado)
        self.labelCargo.setMinimumSize(QtCore.QSize(0, 35))
        self.labelCargo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCargo.setObjectName("labelCargo")
        self.gridLayout_2.addWidget(self.labelCargo, 1, 0, 1, 1)
        self.inputCargo = QtWidgets.QComboBox(insertarImputado)
        self.inputCargo.setMinimumSize(QtCore.QSize(0, 35))
        self.inputCargo.setObjectName("inputCargo")
        self.gridLayout_2.addWidget(self.inputCargo, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelRH = QtWidgets.QLabel(insertarImputado)
        self.labelRH.setMinimumSize(QtCore.QSize(0, 35))
        self.labelRH.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRH.setObjectName("labelRH")
        self.gridLayout_3.addWidget(self.labelRH, 0, 0, 1, 1)
        self.inputGrupoRH = QtWidgets.QComboBox(insertarImputado)
        self.inputGrupoRH.setMinimumSize(QtCore.QSize(0, 35))
        self.inputGrupoRH.setObjectName("inputGrupoRH")
        self.gridLayout_3.addWidget(self.inputGrupoRH, 0, 1, 1, 1)
        self.labelFecha = QtWidgets.QLabel(insertarImputado)
        self.labelFecha.setMinimumSize(QtCore.QSize(0, 35))
        self.labelFecha.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFecha.setObjectName("labelFecha")
        self.gridLayout_3.addWidget(self.labelFecha, 1, 0, 1, 1)
        self.inputFecha = QtWidgets.QDateEdit(insertarImputado)
        self.inputFecha.setMinimumSize(QtCore.QSize(0, 35))
        self.inputFecha.setAlignment(QtCore.Qt.AlignCenter)
        self.inputFecha.setObjectName("inputFecha")
        self.gridLayout_3.addWidget(self.inputFecha, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.botonAceptar = QtWidgets.QPushButton(insertarImputado)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonAceptar.sizePolicy().hasHeightForWidth())
        self.botonAceptar.setSizePolicy(sizePolicy)
        self.botonAceptar.setMinimumSize(QtCore.QSize(150, 40))
        self.botonAceptar.setMaximumSize(QtCore.QSize(200, 40))
        self.botonAceptar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonAceptar.setObjectName("botonAceptar")
        self.horizontalLayout_2.addWidget(self.botonAceptar)
        self.botonCancelar = QtWidgets.QPushButton(insertarImputado)
        self.botonCancelar.setMinimumSize(QtCore.QSize(100, 40))
        self.botonCancelar.setMaximumSize(QtCore.QSize(100, 40))
        self.botonCancelar.setObjectName("botonCancelar")
        self.horizontalLayout_2.addWidget(self.botonCancelar)
        self.botonResetear = QtWidgets.QPushButton(insertarImputado)
        self.botonResetear.setMinimumSize(QtCore.QSize(150, 40))
        self.botonResetear.setMaximumSize(QtCore.QSize(150, 40))
        self.botonResetear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonResetear.setObjectName("botonResetear")
        self.horizontalLayout_2.addWidget(self.botonResetear)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)

        self.retranslateUi(insertarImputado)
        QtCore.QMetaObject.connectSlotsByName(insertarImputado)

    def retranslateUi(self, insertarImputado):
        _translate = QtCore.QCoreApplication.translate
        insertarImputado.setWindowTitle(_translate("insertarImputado", "Insertar Imputado"))
        self.labelNombre.setText(_translate("insertarImputado", "Nombre del Imputado"))
        self.labelApellidos.setText(_translate("insertarImputado", "Apellidos del Imputado"))
        self.labelPartido.setText(_translate("insertarImputado", "Partido Político"))
        self.labelCargo.setText(_translate("insertarImputado", "Cargo Político"))
        self.labelRH.setText(_translate("insertarImputado", "Grupo Sanguíneo"))
        self.labelFecha.setText(_translate("insertarImputado", "Fecha de Nacimiento"))
        self.botonAceptar.setText(_translate("insertarImputado", "Insertar Imputado"))
        self.botonCancelar.setText(_translate("insertarImputado", "Cancelar"))
        self.botonResetear.setText(_translate("insertarImputado", "Resetear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    insertarImputado = QtWidgets.QDialog()
    ui = Ui_insertarImputado()
    ui.setupUi(insertarImputado)
    insertarImputado.show()
    sys.exit(app.exec_())

